### ISSUE TITLE
New Instance of Commands every time a button is pressed. 

### ISSUE THREAD

**Issue by manpreet-singh** [KentridgeRobotics/2019Robot#91]
https://github.com/KentridgeRobotics/2019Robot/blob/2637fefb02e2804ef0e60b4be8fc0ab535ef1fbf/src/main/java/org/usfirst/frc/team3786/robot/Mappings.java#L44-L67

The current code is making a brand new instance of the command every time any of the button is pressed. It would still work the same if the command were only initialized once and then assigned to the button. This way it's not making brand new instances every time a button is pressed it just reusing the command that is already there. This would require you guys to make a small change to the commands. Not sure who wrote these commands but they should be calling other methods from the execute() method instead of the initialize() method.

**Comment by manpreet-singh** [comment]
https://github.com/KentridgeRobotics/2019Robot/blob/2637fefb02e2804ef0e60b4be8fc0ab535ef1fbf/src/main/java/org/usfirst/frc/team3786/robot/commands/elevator/ElevatorUpCommand.java#L17-L25

This here is a good example, the ElevatorSubsystem.getInstance().setElevatorSpeed(0.5); should be under execute(), not initialize().

**Comment by cpdupuis** [comment]
Hi Manpreet,

The "new Command()" calls here are only evaluated when setupDefaultMappings is called. The calls to "Button.whenPressed" and similar methods take in an instance of Command. They don't have the ability to create new instances.

The call to setElevatorSpeed in ElevatorUpCommand is only needed in initialize because this comment is mapped to a "whenPressed" button event, which is then stopped by a call to setElevatorSpeed(0) in ElevatorStopCommand, which is mapped to the corresponding "whenReleased" button event. We're probably going to switch these over to use "whenHeld", which would mean running the "setElevatorSpeed" (or whatever) from execute(), rather than initialize().

Thanks,
Chris
